- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "deploy backend app to new location"
  become_user: ubuntu
  unarchive:
    src: app.tar.gz
    dest: /home/ubuntu/
    
- name: "Unpack app.tar.gz files"
  become: true
  shell: |
    cd /home/ubuntu/
    tar xzvf app.tar.gz
    rm app.tar.gz

- name: "running backend app"
  become_user: ubuntu
  shell: |
    cd /home/ubuntu/dist
    #npm i    
    pm2 start main.js --update-env