- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "deploy backend app to new location"
  become: true
  copy:
    src: app.tar.gz
    dest: /home/ubuntu/
    
- name: "Unpack app.tar.gz files"
  become: true
  shell: |
    cd /home/ubuntu/
    tar xzvf app.tar.gz
    rm app.tar.gz
    ls

- name: "running backend app"
  become: true
  shell: |
    export NODE_ENV=Production
    export ENVIRONMENT=Production
    export VERSION=1
    export TYPEORM_CONNECTION=postgres
    export TYPEORM_MIGRATIONS_DIR=./src/migrations
    export TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
    export TYPEORM_MIGRATIONS=./src/migrations/*.ts
    # Use these values for the local PG database from the Docker Compose file
    export TYPEORM_HOST=udapeople-prod.csghw51ceft2.us-west-2.rds.amazonaws.com
    export TYPEORM_PORT: 5432
    export TYPEORM_USERNAME: postgres
    export TYPEORM_PASSWORD: udapeople123
    export TYPEORM_DATABASE: postgres
    cd /home/ubuntu/dist
    pm2 start main.js
    
    